<a href="https://colab.research.google.com/github/rahu-l-gupta/Analytics_Vidhya/blob/master/1_Tensor_basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
x = torch.tensor([2.])
print(x)
print(x.dtype)

tensor([2.])
torch.float32


In [6]:
y = torch.tensor([[1 ,2, 5], 
                  [3, 4, 6]])
print(y)
print(y.dtype)
print(y.shape)

tensor([[1, 2, 5],
        [3, 4, 6]])
torch.int64
torch.Size([2, 3])


In [11]:
z = torch.tensor([[[1, 2, 3],
                   [4, 5, 6]],
                  [[7, 8, 9],
                   [10, 11, 12]]])
print(z)
print(z.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])


**Gradient operations on tensors**

In [12]:
a = torch.tensor([3.], requires_grad=True)
b = torch.tensor([4.], requires_grad=True)
c = torch.tensor([5.], requires_grad=True)

In [14]:
d = a * b + c
print(d)

tensor([17.], grad_fn=<AddBackward0>)
